# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb0d7fd7f06bf4a12a0e6a9a96c92def37829660dd7c44a6588c229dc1012f6a47a412645a0bf14d9f9fc448ff4f4e74bd3df9c88da839cb27bffaf429a27d5

test:
  secret_key_base: 3c1aec9600d838284298e6373e28f9c3d75645b2524ac03637d9c2d4293178816b4326eb4db82d9edc6ea0f120f5fb94006f3e5531fc1e7ea1739bd92312060e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
